server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.174.128:1111 # 表面上配置的时Nginx,实际上会被映射到Nacos集群上
      #server-addr: 192.168.174.128:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'